# Generated by Django 4.0 on 2021-12-14 20:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=300)),
                ('optionA', models.CharField(max_length=300)),
                ('optionB', models.CharField(max_length=300)),
                ('optionC', models.CharField(max_length=300)),
                ('optionD', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=300)),
            ],
        ),
    ]
