# Generated by Django 4.0 on 2021-12-15 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionbank',
            old_name='answer',
            new_name='correct_answer',
        ),
    ]
